### ISSUE TITLE
noch zu machen:

### ISSUE THREAD

**Issue by Herr-Sepp** [s73331/rnks-apl#1]
Was passiert wenn der Kack-Server etwas NACK_T was außerhalb des Fensters liegt?

Kack Server muss Fenster von Client übergeben bekommen und auch umsetzten
(sendet jetzt NACK immer nur vom letzten bis es das hat und kümmert sich erst dann um andere die eigentlich da sein müssten)

Einstellen des Timeouts

sonst sieht es eigentlich richtig gut aus

Und mein Git konfigurieren, dass ich nicht als S73331 commite ...

**Comment by J4nn1s** [comment]
"Was passiert wenn der Kack-Server etwas NACK_T was außerhalb des Fensters liegt?"
--> dürfte doch theoretisch garnicht passieren oder? ich würde close senden

**Comment by s73331** [comment]
git config --global user.name "Sepp"
